config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :books

  get 'home/index'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :author, :editorial, :presence => true
  validates :edition, :publication_year, numericality: { only_integer: true, greater_than: 0 }, allow_nil: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  respond_to :html
  before_action :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    @book.save
  end

  def update
    @book.update(book_params)
  end

  def destroy
    @book.destroy
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :author, :editorial, :original_title, :translation, :edition, :edition_date, :edition_place, :publication_year, :isbn)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user.nil?
      redirect_to new_user_session_path
    else
      redirect_to books_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :editorial %><br>
    <%= f.text_field :editorial %>
  </div>
  <div class="field">
    <%= f.label :original_title %><br>
    <%= f.text_field :original_title %>
  </div>
  <div class="field">
    <%= f.label :translation %><br>
    <%= f.text_field :translation %>
  </div>
  <div class="field">
    <%= f.label :edition %><br>
    <%= f.number_field :edition %>
  </div>
  <div class="field">
    <%= f.label :edition_date %><br>
    <%= f.date_select :edition_date %>
  </div>
  <div class="field">
    <%= f.label :edition_place %><br>
    <%= f.text_field :edition_place %>
  </div>
  <div class="field">
    <%= f.label :publication_year %><br>
    <%= f.number_field :publication_year %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<% content_for :title, "Lista de libros" %>
<div id="books_index">
  <h1><%= yield :title %></h1>

  <% if @books.blank? %>
    <div class="alert alert-warning">No hay libros que mostrar</div>
  <% else %>
    <div class="responsive-fake-table expansible-fake-table">
      <header class="row">
        <div class="col col-xs-5 col-sm-4 col-md-3"><%=t('activerecord.attributes.book.title')%></div>
        <div class="col col-xs-4 col-sm-3 col-md-3"><%=t('activerecord.attributes.book.author')%></div>
        <div class="col hidden-xs col-sm-3 col-md-3"><%=t('activerecord.attributes.book.editorial')%></div>
        <div class="col hidden-xs hidden-sm col-md-1"><%=t('activerecord.attributes.book.edition')%></div>
        <div class="col col-xs-3 col-sm-2 col-md-2"><span class="hidden-sm hidden-xs">Opciones</span>&nbsp;</div>
      </header>
      <% @books.each do |book|%>
        <section class="row">
          <div class="col col-xs-5 col-sm-4 col-md-3 toggle"><%=book.title %></div>
          <div class="col col-xs-4 col-sm-3 col-md-3 toggle"><%=book.author%></div>
          <div class="col hidden-xs col-sm-3 col-md-3 toggle"><%=book.editorial%></div>
          <div class="col hidden-xs hidden-sm col-md-1 toggle"><%=book.edition%></div>
          <div class="col col-xs-3 col-sm-2 col-md-2">
            <%= link_to 'Ver', book, class: 'tooltipable' %>
            <%= link_to 'Editar', edit_book_path(book), class: 'tooltipable' %>
            <%= link_to 'Borrar', book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'tooltipable' %>

          </div>
          <div class="col col-xs-12 panel-collapse collapse">
            <dl class="dl-horizontal">

              <dt class="visible-xs"><%=t('activerecord.attributes.book.editorial') %></dt>
              <dd class="visible-xs"><%=book.editorial || '-' %></dd>

              <dt><%=t('activerecord.attributes.book.original_title') %></dt>
              <dd><%=book.original_title || '-' %></dd>

              <dt class="visible-xs visible-sm"><%=t('activerecord.attributes.book.edition') %></dt>
              <dd class="visible-xs visible-sm"><%=book.edition || '-' %></dd>

              <dt><%=t('activerecord.attributes.book.edition_date') %></dt>
              <dd><%=book.edition_date.present? ? l(book.edition_date) : '-' %></dd>

              <dt><%=t('activerecord.attributes.book.publication_year') %></dt>
              <dd><%=book.publication_year || '-' %></dd>

              <dt></dt>
              <dd>
              </dd>
            </dl>
            <%= link_to 'Ver más', book, class: 'btn btn-default btn-xs more-book-btn' %>
          </div>
        </section>
      <% end %>
    </div>
  <% end %>

  <%= link_to 'Agregar libro', new_book_path, class: 'btn btn-primary' %>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<% content_for :title, "Ver libro: #{@book.title}" %>
<div id="books_show">
  <h1><%= yield :title %></h1>
  <dl class="dl-horizontal">
    <dt><%=t('activerecord.attributes.book.title') %></dt>
    <dd><%=@book.title || '-' %></dd>
    <dt><%=t('activerecord.attributes.book.author') %></dt>
    <dd><%=@book.author || '-' %></dd>
    <dt><%=t('activerecord.attributes.book.editorial') %></dt>
    <dd><%=@book.editorial || '-' %></dd>
    <dt><%=t('activerecord.attributes.book.original_title') %></dt>
    <dd><%=@book.original_title || '-' %></dd>
    <dt><%=t('activerecord.attributes.book.translation') %></dt>
    <dd><%=@book.translation || '-' %></dd>
    <dt><%=t('activerecord.attributes.book.edition') %></dt>
    <dd><%=@book.edition || '-' %></dd>
    <dt><%=t('activerecord.attributes.book.edition_date') %></dt>
    <dd><%=if @book.edition_date.present? then l(@book.edition_date) else '-' end %></dd>
    <dt><%=t('activerecord.attributes.book.edition_place') %></dt>
    <dd><%=@book.edition_place || '-' %></dd>
    <dt><%=t('activerecord.attributes.book.publication_year') %></dt>
    <dd><%=@book.publication_year || '-' %></dd>
    <dt><%=t('activerecord.attributes.book.isbn') %></dt>
    <dd><%=@book.isbn || '-' %></dd>
  </dl>
  <div class="row">
    <div class="col-sm-offset-1 col-sm-11">
      <%= link_to 'Editar', edit_book_path(@book), class: 'btn btn-primary' %>
      <%= link_to 'Volver', books_path, class: 'btn btn-default' %>
    </div>
  </div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<p><%if user_signed_in? %>
  Hola <%= current_user.as_json.inspect %> - <%=link_to 'salir', destroy_user_session_path, :method => :delete  %> 
  <% else %>
  <%= link_to 'ingresar', new_user_session_path %>
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>La biblio<%= (" :: " + yield(:title)) if content_for?(:title)  %></title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>
<body>

  <% if current_user.present? %>
    <header>
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapsible-at-xs">
              <span class="sr-only">Abre / cierra la navegación</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'La biblio', root_path, class: 'navbar-brand'%>
          </div>

          <div class="collapse navbar-collapse" id="main-navbar-collapsible-at-xs">



            <ul class="nav navbar-nav navbar-right">
              <li>
                <%=link_to destroy_user_session_path, method: :delete do %>
                  salir <i class="fa fa-sign-out"></i>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  <% end %>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= notice %>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>